[versions]
android-compileSdk = "35"
android-minSdk = "33"
androidx-activity = "1.9.2"
androidx-paging = "3.3.2"
cash-sqldelight = "2.0.2"
coil-kt = "3.0.0-rc01"
compose-plugin = "1.7.0"
detekt = "1.23.7"
gitlive-firebase = "2.1.0"
google-accompanist = "0.36.0"
google-android = "8.7.1"
google-maps-compose = "4.3.2"
google-services = "4.4.2"
jetbrains-kotlin = "2.0.21"
kotlin-jvmTarget = "17"
kotlinx-coroutines = "1.9.0"
kotlinx-serialization = "1.7.3"
ktor = "3.0.0"
pinterest-ktlint = "0.50.0"
slack-circuit = "0.24.0"

[libraries]
ajalt-clikt = "com.github.ajalt.clikt:clikt:5.0.1"
android-tools-desugarjdk = "com.android.tools:desugar_jdk_libs:2.1.2"

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-annotation = "androidx.annotation:annotation:1.8.2"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-credentials-auth = "androidx.credentials:credentials-play-services-auth:1.3.0"
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }

app-cash-turbine = "app.cash.turbine:turbine:1.1.0"

auth-java-jwt = "com.auth0:java-jwt:4.4.0"
auth-jwks-rsa = "com.auth0:jwks-rsa:0.22.1"

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil-kt" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor2", version.ref = "coil-kt" }

detekt-compose = "io.nlopez.compose.rules:detekt:0.4.16"
detekt-formatatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

fasterxml-jackson-core = "com.fasterxml.jackson.core:jackson-core:2.18.0"
fusesource-jansi = "org.fusesource.jansi:jansi:2.4.1"

gitlive-firebase-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "gitlive-firebase" }
gitlive-firebase-app = { module = "dev.gitlive:firebase-app", version.ref = "gitlive-firebase" }
gitlive-firebase-config = { module = "dev.gitlive:firebase-config", version.ref = "gitlive-firebase" }

google-accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "google-accompanist" }
google-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "google-accompanist" }

google-android-identity = "com.google.android.libraries.identity.googleid:googleid:1.1.1"
google-android-location = "com.google.android.gms:play-services-location:21.3.0"
google-android-material = "com.google.android.material:material:1.12.0"

google-auth-http = "com.google.auth:google-auth-library-oauth2-http:1.28.0"
google-cloud-bom = "com.google.cloud:libraries-bom:26.48.0"
google-cloud-firestore = { module = "com.google.cloud:google-cloud-firestore" }

google-firebase-admin = "com.google.firebase:firebase-admin:9.3.0"
google-firebase-bom = "com.google.firebase:firebase-bom:33.4.0"
google-firebase-appcheck-playintegrity = { module = "com.google.firebase:firebase-appcheck-playintegrity" }

google-guava-jre = "com.google.guava:guava:33.3.1-jre"

google-maps-android-compose = "com.google.maps.android:maps-compose:6.1.2"
google-maps-android-utils = "com.google.maps.android:android-maps-utils:3.8.2"

kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.8"

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.1"

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "kotlinx-serialization" }

ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-io = { module = "io.ktor:ktor-io", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-conditional-headers = { module = "io.ktor:ktor-server-conditional-headers", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

mosaic-runtime = "com.jakewharton.mosaic:mosaic-runtime:0.14.0"
pinterest-ktlint-bom = "com.pinterest.ktlint:ktlint-bom:1.3.1"

slack-circuit-foundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "slack-circuit" }
slack-circuit-runtime = { module = "com.slack.circuit:circuit-runtime", version.ref = "slack-circuit" }
slack-circuit-overlay = { module = "com.slack.circuit:circuit-overlay", version.ref = "slack-circuit" }
slack-circuit-test = { module = "com.slack.circuit:circuit-test", version.ref = "slack-circuit" }

slf4j-simple = "org.slf4j:slf4j-simple:2.0.16"

sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "cash-sqldelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "cash-sqldelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "cash-sqldelight" }
sqldelight-paging3-extensions = { module = "app.cash.sqldelight:androidx-paging3-extensions", version.ref = "cash-sqldelight" }
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "cash-sqldelight" }

squareup-okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
squareup-okio = "com.squareup.okio:okio:3.9.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "google-android" }
android-library = { id = "com.android.library", version.ref = "google-android" }
build-config = "com.github.gmazzo.buildconfig:5.5.0"
cash-sqldelight = { id = "app.cash.sqldelight", version.ref = "cash-sqldelight" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrains-kotlin" }
dependency-analysis = "com.autonomousapps.dependency-analysis:2.1.4"
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
gradle-doctor = "com.osacky.doctor:0.10.0"
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrains-kotlin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.8.3"
ktlint = "org.jlleitschuh.gradle.ktlint:12.1.1"
openapi-generator = "org.openapi.generator:7.9.0"
